### PR TITLE
Create a TODO Product

### PR DESCRIPTION
**Pull request by dipsetipse**
Added basic product requirements for the TODO product

### CODE REVIEW

**Comment by dipsetipse** [comment]
I think this is a very complex website.

**Comment by dipsetipse** [comment]
This is a very complex website

**Comment by Ping-Xu01** [comment]
review completed

**Comment by Ping-Xu01** [comment]
review completed

**Comment by Ping-Xu01** [comment]
review  completed 3

**Comment by Ping-Xu01** [comment]
reviewed 4

**Pull request merged**
